version: '3'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_URL=postgresql://user:password@postgres:5432/mydatabase
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:latest"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
